# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/softly/game/shade/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/softly/game/shade

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/softly/game/shade/CMakeFiles /home/softly/game/shade/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/softly/game/shade/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shade

# Build rule for target.
Shade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Shade
.PHONY : Shade

# fast build rule for target.
Shade/fast:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/build
.PHONY : Shade/fast

gui/gui.o: gui/gui.c.o
.PHONY : gui/gui.o

# target to build an object file
gui/gui.c.o:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/gui/gui.c.o
.PHONY : gui/gui.c.o

gui/gui.i: gui/gui.c.i
.PHONY : gui/gui.i

# target to preprocess a source file
gui/gui.c.i:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/gui/gui.c.i
.PHONY : gui/gui.c.i

gui/gui.s: gui/gui.c.s
.PHONY : gui/gui.s

# target to generate assembly for a file
gui/gui.c.s:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/gui/gui.c.s
.PHONY : gui/gui.c.s

model/model.o: model/model.c.o
.PHONY : model/model.o

# target to build an object file
model/model.c.o:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/model/model.c.o
.PHONY : model/model.c.o

model/model.i: model/model.c.i
.PHONY : model/model.i

# target to preprocess a source file
model/model.c.i:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/model/model.c.i
.PHONY : model/model.c.i

model/model.s: model/model.c.s
.PHONY : model/model.s

# target to generate assembly for a file
model/model.c.s:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/model/model.c.s
.PHONY : model/model.c.s

shade.o: shade.c.o
.PHONY : shade.o

# target to build an object file
shade.c.o:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/shade.c.o
.PHONY : shade.c.o

shade.i: shade.c.i
.PHONY : shade.i

# target to preprocess a source file
shade.c.i:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/shade.c.i
.PHONY : shade.c.i

shade.s: shade.c.s
.PHONY : shade.s

# target to generate assembly for a file
shade.c.s:
	$(MAKE) -f CMakeFiles/Shade.dir/build.make CMakeFiles/Shade.dir/shade.c.s
.PHONY : shade.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Shade"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gui/gui.o"
	@echo "... gui/gui.i"
	@echo "... gui/gui.s"
	@echo "... model/model.o"
	@echo "... model/model.i"
	@echo "... model/model.s"
	@echo "... shade.o"
	@echo "... shade.i"
	@echo "... shade.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

